### ISSUE TITLE
Does FastDev disable itself when DEBUG==False?

### ISSUE THREAD

**Issue by mjmare** [boxed/django-fastdev#35]
Or should I conditionally install FastDev?

TIA

**Comment by boxed** [comment]
It does not. This is very much on purpose! It is MUCH more important that you get a crash in prod than in testing when you hit a bad template bug. If the error is silent (like django is by default) the page will be broken for eternity.

**Comment by mjmare** [comment]
Oh my bad, of course I meant DEBUG==False. Sorry.

**Comment by boxed** [comment]
I read it as such. My answer above is for the question as you intended it. Fastdev must always be enabled.

**Comment by mjmare** [comment]
Hmmm, makes sense. But then you probably also setup something like sentry or rollbar, that will probably pick up the exception, right?

**Comment by boxed** [comment]
Oh for sure. A production deploy without Sentry is not really a production deploy at all :P I have sentry set up on small silly hobby projects too.

**Comment by boxed** [comment]
I've only used Sentry so I don't know.

**Comment by mjmare** [comment]
Thx
