### ISSUE TITLE
gitignore validation is misleading

### ISSUE THREAD

**Issue by danlamanna** [boxed/django-fastdev#37]
Hey, thanks for the package, it's a lifesaver in the dynamic world of Django :)

I just noticed that all of a sudden fastdev is complaining about my virtual environment missing from `.gitignore`. It also appears to erroneously print to `stdout` which breaks scripts that utilize output from `manage.py` invocations.

My virtual environment is in `~/.config/git/ignore` so it *is* ignored, but the error message still appears because it's not in the project specific `.gitignore`. Utilizing [git check-ignore](https://git-scm.com/docs/git-check-ignore) might be a more accurate way to check which items git ignores.

Finally, I wonder if this check is entirely out-of-scope for a django development app. Migrations are django-specific, but virtualenvs, pycache directories, etc are general to all python projects and I'm not sure django-fastdev should be ever-expanding in its scope to all of the various items that are typically ignored. What do you think?

**Comment by boxed** [comment]
Fastdev has grown to be also a tool to help beginners not make mistakes. So yea, the scope of the project itself is a bit fuzzy :)

I'm very open to a PR that does something smarter.
