### ISSUE TITLE
InvalidCleanMethod clean_email2 when using django-allauth 

### ISSUE THREAD

**Issue by Tobi-De** [boxed/django-fastdev#42]
Hi, me again and with an issue very similar to #23
Allauth seems to have an `email2` field and a `ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE` which is false by default, so there is a problematic and useless in my case `clean_email2` field, this is my current workaround

```python
from allauth.account.forms import SignupForm


class UserSignupForm(SignupForm):
    # This prevent django-fastdev from raising an error when accessing the signup page
    clean_username = None
    clean_email2 = None

```
I also don't require the username so the the field is not present on the form
a better idea ?

**Comment by boxed** [comment]
Yea, this seems like a reasonable approach.

**Comment by ramiboutas** [comment]
Hi, those methods (`clean_password1`, `clean_password2`, `clean_email`)   exists but in the [`BaseSignupForm` ](https://github.com/pennersr/django-allauth/blob/main/allauth/account/forms.py#L258).

@boxed, is it possible to implement these checks in the base classes?

**Comment by boxed** [comment]
Did you paste the wrong link? Because it doesn't lead to any of those.
