### ISSUE TITLE
Version 1.10.0 - "invalid blocks specified" in Django admin site

### ISSUE THREAD

**Issue by patknight** [boxed/django-fastdev#47]
Django 5.1.2
django-fastdev 1.10.0
DEBUG = True

1.10.0 fails with the exception 'invalid blocks specified' - exception page extract below.

1.9.0 works fine. My own pages seem unaffected. Please let me know what additional info you need.

PS - I'm the Pat you've helped a lot on the iommi discourse :-) 

Extract from settings.py:
``` python
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_fastdev',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

```

Visiting localhost:8000/admin with 1.10.0 shows the exception page:
``` html
<h1>Exception
       at /admin/</h1>
  <pre class="exception_value">Invalid blocks specified:

    nav-breadcrumbs
    nav-sidebar

Valid blocks:

    blockbots
    bodyclass
    branding
    coltype
    content
    content_subtitle
    content_title
    dark-mode-vars
    extrahead
    extrastyle
    footer
    messages
    nav-global
    object-tools
    pretitle
    responsive
    sidebar
    stylesheet
    title</pre>
  
Request Method: | GET
-- | --
http://localhost:8800/admin/
5.1.2
Exception
Invalid blocks specified:      nav-breadcrumbs     nav-sidebar  Valid blocks:      blockbots     bodyclass     branding     coltype     content     content_subtitle     content_title     dark-mode-vars     extrahead     extrastyle     footer     messages     nav-global     object-tools     pretitle     responsive     sidebar     stylesheet     title
/home/pat/git/djangomoney/lib/python3.12/site-packages/django_fastdev/apps.py, line 428, in extends_render
django.contrib.admin.sites.index
/home/pat/git/djangomoney/bin/python
3.12.6
['/home/pat/git/djangomoney',  '/home/pat/git/djangomoney',  '/home/pat/pycharm/plugins/python-ce/helpers/pycharm_display',  '/usr/lib/python312.zip',  '/usr/lib/python3.12',  '/usr/lib/python3.12/lib-dynload',  '/home/pat/git/djangomoney/lib/python3.12/site-packages',  '/home/pat/pycharm/plugins/python-ce/helpers/pycharm_matplotlib_backend',  '/home/pat/pycharm/plugins/python-ce/helpers/pycharm_plotly_backend']
Tue, 08 Oct 2024 15:01:02 -0400
```

``` html
<h2>Error during template rendering</h2>
   <p>In template <code>/home/pat/git/djangomoney/lib/python3.12/site-packages/django/contrib/admin/templates/admin/index.html</code>, error at line <strong>1</strong></p>
   <h3>Invalid blocks specified:

    nav-breadcrumbs
    nav-sidebar

Valid blocks:

    blockbots
    bodyclass
    branding
    coltype
    content
    content_subtitle
    content_title
    dark-mode-vars
    extrahead
    extrastyle
    footer
    messages
    nav-global
    object-tools
    pretitle
    responsive
    sidebar
    stylesheet
    title</h3>
   
1 | {% extends "admin/base_site.html" %}
-- | --
{% load i18n static %}
 
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/dashboard.css" %}">{% endblock %}
 
{% block coltype %}colMS{% endblock %}
 
{% block bodyclass %}{{ block.super }} dashboard{% endblock %}
 
{% block nav-breadcrumbs %}{% endblock %}
```

**Comment by patknight** [comment]
To reproduce the issue

1. Create venv and install Django 5.1.2, django-fastdev 1.10.0
2. Follow the Django getting started (or your own experience) to create a minimal Django project and app.
3. Add django-fastdev to the end of INSTALLED_APPS in settings.py
4. Run python manage.py migrate
5. Run python manage.py runserver
6. Visit the localhost:8000/admin link and see the traceback.

**Comment by patknight** [comment]
I've been doing some debugging. Line numbers refer to Django 5.1.2 and django-fastdev 1.10.0.

So the immediate cause of the missing blocks `nav-breadcrumbs`,  `nav-sidebar`, and `usertools` is that they're guarded by an `{% if not is_popup %}` at line 32 of `.../.lib/python3.12/site-packages/django/contrib/admin/templates/admin/base.html`. This appears to prevent the template compilation triggered by fastdev's `get_extend_nodes_parent` from finding the offending blocks.

I'll do some more digging into change histories to see what's causing this.

**Comment by patknight** [comment]
OK - it looks like change [d597e615 Anders Hovmöller <anders.hovmoller@dryft.se> ](https://github.com/boxed/django-fastdev/commit/d597e615bdd4834555dd42464c06d588a8ec5d51) is the root cause. It's an interaction between block validation (definitely want this) and Django template conditional block definition handling. Over to you, @boxed , this is beyond me!

**Comment by boxed** [comment]
Thanks! Fixed now and released in 1.11.0

**Comment by patknight** [comment]
Sorry @boxed  :-(, but you might want to reopen this. I just tested and I'm seeing the same issue. I'll keep digging into Django, but I think the issue might be that the Django Template parser doesn't add `block` definitions inside the `if false` -
``` html
{% if var_with_value_false %}
    {% block this_is_not_added_to_the_nodelist %} {% endblock %}
{% else %}
    {% block this_is_added_to_the_nodelist %} {% endblock %}
{% endif %}
```
I'll do some more investigating, but I think that there's nothing you can do by looking at nodelists - Django isn't adding those blocks for you to find. I have a couple of ideas:

- Either we find a way of passing fastdev's instance of the Template parser the same context that Django is using for the page
- or we look at using the Lexer's token stream instead and look for block definition Tokens. I think this will work for fastdev's purposes, but you'd know better.

I hope (family permitting) to spend some time today chasing this.

**Comment by boxed** [comment]
I added a `{% block %}` inside an `{% if %}` to my test case. Hmm.. I did find an issue that `{% for %}` had a similar bug though. Maybe that's your case? 

I've pushed the fix for this case, could you try the latest code on master?

**Comment by patknight** [comment]
Will do. `{% for %}` isn't the issue I'm seeing. The missing blocks are in an `{% if %}` starting at line 32 of `.../.lib/python3.12/site-packages/django/contrib/admin/templates/admin/base.html` (Django version 5.1.2)

**Comment by patknight** [comment]
After I fixed the problem in https://github.com/boxed/django-fastdev/issues/47#issuecomment-2408610254, the original exception returned. Looking at the context, it is the one Django is using to render the page, which invalidates my first assumption in https://github.com/boxed/django-fastdev/issues/47#issuecomment-2408585873. So I'm going to have do more digging into what Django is doing.

@boxed - Sorry to be so chatty in the comments, but I want to keep you up to date with what I'm trying as you seem to be working on this too. I can keep commenting here, or do you have a Discord for fastdev?

**Comment by boxed** [comment]
I don't have a discord, but you can use the Unofficial Django Discord or iommi offtopic channels

**Comment by patknight** [comment]
I have a candidate fix - see the new pull request. What was happening is that `collect_valid_blocks` needs to also collect nested blocks from `IfNode` and `ForNode` to find the conditionally defined blocks. Please review in case the patch makes the code too lenient now, but at least the exception has gone away.

**Comment by boxed** [comment]
I released 1.12.0 with this fix

**Comment by patknight** [comment]
> I released 1.12.0 with this fix

Thanks

**Comment by patknight** [comment]
> I wonder if this is too narrow too... but yea, it's a lot better at least.

Good point. I'm going through the Django source now to look at other node types.

**Comment by patknight** [comment]
I ended up with
``` python
        def collect_valid_blocks(template, context):
            result = set()
            for x in template.nodelist:
                
                if isinstance(x, (ExtendsNode, IncludeNode)):
                    result |= collect_nested_blocks(x)
                    result |= collect_valid_blocks(get_extends_node_parent(x, context), context)
                elif hasattr(x, 'child_nodelists'):
                    # to be more explicit, could make the condition above
                    # isinstance(x, (AutoEscapeControlNode, BlockNode, FilterNode, ForNode, IfNode,
                    # IfChangedNode, SpacelessNode))
                    result |= collect_nested_blocks(x)
            return result
```
but I'm worried this may have opened the floodgates. We could use the explicit list of nodes, but this is future proof.

Please let me know if you want a pull request.

**Comment by patknight** [comment]
After thinking overnight, and some checking this morning, we don't need to do special handling for `IncludeNode`. It appears to be wrapped in a `BlockNode` and so get's processed as part of that. I ended up with:
``` python
        def collect_valid_blocks(template, context):
            result = set()
            for x in template.nodelist:
                if isinstance(x, ExtendsNode):
                    result |= collect_nested_blocks(x)
                    result |= collect_valid_blocks(get_extends_node_parent(x, context), context)
                elif hasattr(x, 'child_nodelists'):
                    # to be more explicit, could make the condition above
                    # 'isinstance(x, (AutoEscapeControlNode, BlockNode, FilterNode, ForNode, IfNode,
                    # IfChangedNode, SpacelessNode))' at the risk of missing some we don't know about
                    result |= collect_nested_blocks(x)
            return result
```
and am submitting a pull request.
